---
language: python
services: docker

env:
  global:
    - ROLE_NAME: graylog_collector
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: debian8
    - MOLECULE_DISTRO: debian9

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-graylog-collector mklettner.$ROLE_NAME
  - cd mklettner.$ROLE_NAME

script:
  # Run tests.9
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
