---
# Variable configuration.

- name: Include OS-specific variables (RedHat).
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  when: ansible_os_family == "RedHat"

- name: Include OS-specific variables (Debian).
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "Debian" and ansible_distribution != 'Ubuntu'

- name: Include OS-specific variables (Ubuntu).
  include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_os_family == "Debian" and ansible_distribution == 'Ubuntu'
