FROM centos:6

RUN yum update -y

RUN yum -y install epel-release && yum -y install git ansible sudo

RUN sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/'  /etc/sudoers && echo -e '[local]\nlocalhost ansible_connection=local' > /etc/ansible/hosts


CMD ["/sbin/init"]